name: Update Lambda

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: kazimanzurrashid/aws-lambda-update-action@v2.0.3
      with:
        zip-file: 'dist/lambda_function.zip'
        lambda-name: 'cloudresume-function'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}